---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: repo-utils-shared
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/repo-utils-shared.git
    targetRevision: main
    path: charts/repo-utils-shared
    helm:
      valueFiles: [values.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
