---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base/]
namespace: default
labels:
  - includeSelectors: true
    pairs:
      app: repo-utils-shared
images:
  - name: repo-utils-shared
    newName: repo-utils-shared
    newTag: latest
