---
name: Secret Scanning
on: [push, pull_request]

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Run TruffleHog Action
        uses: trufflesecurity/trufflehog@main
        with:
          path: .                # scan local repo
          base: origin/main      # or mainline branch
          head: HEAD             # current commit
