---
name: Secret Scanning
on: [push, pull_request]
jobs:
  secret-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install TruffleHog
        run: pip install trufflehog
      - name: Run TruffleHog with Soft Fail
        run: |-
          set -e
          trufflehog git file://. --json > trufflehog-output.json || status=$?
          if [ "$status" -eq 183 ]; then
            echo "⚠️ TruffleHog found unverified secrets (not fatal)"
          elif [ "$status" -ne 0 ]; then
            echo "❌ TruffleHog failed with status $status"
            exit $status
          fi
